# Generated by Django 3.0.1 on 2019-12-28 08:40

from django.db import migrations, models

def break_text(apps, schema_editor):
    shout = apps.get_model("master", "Shout")
    for shouts in shout.objects.all():
        if len(shouts.body) > 420:
            shouts.body = shouts.body[0:420]
            shouts.save()

class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(break_text),
        migrations.AlterField(
            model_name='shout',
            name='body',
            field=models.CharField(max_length=420),
        ),
    ]
