# Generated by Django 2.2.3 on 2019-08-10 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20190810_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=150)),
                ('body', models.CharField(max_length=9999)),
                ('sentiment', models.CharField(default='NEUTRAL', max_length=8)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('shouter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supporting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('shout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='master.Shout')),
                ('supporters', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='advice',
            name='shout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Shout'),
        ),
        migrations.DeleteModel(
            name='Shouts',
        ),
    ]
