# Generated by Django 2.2.3 on 2019-08-10 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20190810_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='shout',
            name='supporters',
            field=models.ManyToManyField(related_name='shout_supporters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shout',
            name='shouter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shout_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Supporting',
        ),
    ]
