# Generated by Django 2.2.3 on 2019-08-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_auto_20190810_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='shout',
            name='slug',
            field=models.SlugField(default=None, max_length=40),
            preserve_default=False,
        ),
    ]
