# Generated by Django 2.2.3 on 2019-08-14 04:45

from django.db import models, migrations
from django.utils.text import slugify


def create_shout_slug(apps, schema_editor):
    Shout = apps.get_model("master", "Shout")
    for shout in Shout.objects.all():
        shout.slug = slugify(shout.title)
        shout.save()

class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_shout_slug'),
    ]

    operations = [
        (migrations.RunPython(create_shout_slug))
    ]
