# Generated by Django 2.2.3 on 2019-08-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_auto_20190814_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shout',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True),
        ),
    ]
