# Generated by Django 2.2.3 on 2019-08-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_remove_shout_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='shout',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True),
        ),
    ]
