# Generated by Django 2.2.3 on 2019-08-14 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0011_auto_20190814_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shout',
            name='slug',
        ),
    ]
