# Generated by Django 2.2.3 on 2019-08-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0013_shout_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shout',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=40, null=True),
        ),
    ]
