# Generated by Django 2.2.3 on 2019-08-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0015_auto_20190830_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='shout',
            name='value',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
