# Generated by Django 2.2.3 on 2019-08-31 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0017_auto_20190831_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='shout',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='master.Shout'),
        ),
    ]
