# Generated by Django 2.2.3 on 2019-08-31 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0018_auto_20190831_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shout',
            name='threshhold',
        ),
        migrations.AddField(
            model_name='shout',
            name='threshold',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
