# Generated by Django 2.2.3 on 2019-09-01 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0019_auto_20190831_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
    ]
