# Generated by Django 2.2.3 on 2019-09-01 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0020_remove_customuser_is_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_comment', 'Can comment in the discussion forum'), ('can_delete', 'Can remove a comment'), ('can_ban', 'Can ban a user')]},
        ),
    ]
