# Generated by Django 2.2.3 on 2019-09-01 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0021_auto_20190901_0850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_comment', 'Can comment in the discussion forum'), ('can_ban', 'Can ban a user')]},
        ),
    ]
