# Generated by Django 2.2.3 on 2019-09-01 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0022_auto_20190901_0854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
    ]
