# Generated by Django 2.2.3 on 2019-09-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0023_auto_20190901_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=40, null=True),
        ),
    ]
