# Generated by Django 2.2.3 on 2019-09-01 12:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0024_comment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid4, editable=False, max_length=80, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shout',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid4, editable=False, max_length=80, null=True, unique=True),
        ),
    ]
