# Generated by Django 2.2.3 on 2019-09-07 05:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0027_auto_20190901_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, max_length=80, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shout',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, max_length=80, null=True, unique=True),
        ),
    ]
