# Generated by Django 2.2.3 on 2019-09-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0028_auto_20190907_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shout',
            name='value',
            field=models.CharField(blank=True, default=None, max_length=9999, null=True),
        ),
    ]
