# Generated by Django 2.2.3 on 2019-09-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0029_auto_20190910_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shout',
            name='value',
            field=models.CharField(blank=True, default=None, max_length=20000, null=True),
        ),
    ]
