# Generated by Django 2.2.3 on 2019-09-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0030_auto_20190910_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shout',
            name='value',
            field=models.BinaryField(blank=True, default=None, max_length=4000, null=True),
        ),
    ]
