# Generated by Django 3.0.1 on 2020-01-02 17:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=499)),
                ('slug', models.SlugField(default=uuid.uuid4, max_length=80, null=True, unique=True)),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(default=uuid.uuid4, max_length=80, null=True, unique=True)),
                ('body', models.CharField(max_length=420)),
                ('sentiment', models.CharField(default='NEUTRAL', max_length=8)),
                ('value', models.BinaryField(blank=True, default=None, max_length=4000, null=True)),
                ('threshold', models.PositiveIntegerField(default=5)),
                ('shouter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shouts', to='profile.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banned', models.ManyToManyField(related_name='banned_user', to='profile.Profile')),
                ('comments', models.ManyToManyField(related_name='discussion_comment', to='shouts.Comment')),
                ('shout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shouts.Shout')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='commented_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shouts.Shout'),
        ),
    ]
