# Generated by Django 2.2 on 2020-02-01 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shout',
            name='value',
        ),
    ]
