# Generated by Django 2.2 on 2020-02-01 07:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shouts', '0002_remove_shout_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='shout',
            name='value',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=16, null=True), null=True, size=768), null=True, size=420),
        ),
    ]
